apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-cert-manager
resources:
  - namespace.yaml
  - resources/cluster-ca.yaml
  - resources/selfsigned-issuer.yaml
helmGlobals:
  chartHome: charts/cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.1
    releaseName: cert-manager
    namespace: core-cert-manager
    valuesFile: resources/values.yaml
