apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
helmCharts:
  - name: argo-cd
    namespace: core-argocd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    includeCRDs: true
    version: 9.1.4
    valuesFile: values.yaml
