apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: core-argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: server.secretkey
      remoteRef:
        key: argocd-server-secretkey
    - secretKey: tls.crt
      remoteRef:
        key: argocd-tls-crt
    - secretKey: tls.key
      remoteRef:
        key: argocd-tls-key
