apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: core-argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: github-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:FailureToLoad/homelab-cluster.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: github-ssh-privatekey
