apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/ExternalSecret--core-argocd--argocd-redis.yaml
  - resources/ExternalSecret--core-argocd--argocd-secret.yaml
  - resources/ExternalSecret--core-argocd--github-credentials.yaml
