apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datamonster
  namespace: core-networking
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`data-monster.net`)
      kind: Rule
      services:
        - name: datamonster
          namespace: datamonster
          port: 80
  tls: {}
