apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: cilium
    namespace: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    includeCRDs: false
    version: 1.18.0
    valuesFile: values.yaml
