apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    namespace: core-cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    includeCRDs: true
    version: 1.19.1
    valuesFile: values.yaml
