apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-postgres
resources:
  - namespace.yaml
helmGlobals:
  chartHome: charts/postgres
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.26.1
    releaseName: cnpg
    namespace: core-postgres
    valuesFile: resources/values.yaml
