apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-auth
resources:
  - namespace.yaml
  - resources/lldap.yaml
  - resources/ingress.yaml
  - resources/authelia-ingress.yaml
helmGlobals:
  chartHome: charts/authelia
helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    version: 0.9.5
    releaseName: authelia
    namespace: core-auth
    valuesFile: resources/authelia-values.yaml
