apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: edge
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    contentTypeNosniff: true
    frameDeny: false
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datamonster
  namespace: edge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`data-monster.net`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: edge
      services:
        - name: datamonster
          namespace: datamonster
          port: 80
  tls:
    secretName: tunnel-wildcard-tls
