apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - tailscale.yaml
  - longhorn-system.yaml
  - observe.yaml
  - valkey.yaml
  - postgres.yaml
  - edge.yaml
  - datamonster.yaml
