apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core-cert-manager.yaml
  - core-cilium.yaml
  - core-external-secrets.yaml
  - core-tailscale.yaml
  - core-argocd.yaml
secretGenerator:
  - name: azure-secret
    namespace: core-external-secrets
    files:
      - client-id=secrets/azure/client-id
      - client-secret=secrets/azure/client-secret
      - tenant-id=secrets/azure/tenant-id
    options:
      disableNameSuffixHash: true
