apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core-cert-manager.yaml
  - core-cilium.yaml
  - core-external-secrets.yaml
secretGenerator:
  - name: azure-secret
    namespace: core-external-secrets
    files:
      - client-id=secrets/azure/client-id
      - client-secret=secrets/azure/client-secret
      - tenant-id=secrets/azure/tenant-id
    options:
      disableNameSuffixHash: true
  - name: cilium-ca
    namespace: core-cilium
    files:
      - secrets/cilium/ca.crt
      - secrets/cilium/ca.key
    options:
      disableNameSuffixHash: true
  - name: hubble-server-certs
    namespace: core-cilium
    files:
      - secrets/cilium/ca.crt
      - secrets/cilium/tls.crt
      - secrets/cilium/tls.key
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
