apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tailscale-operator
    repo: charts/tailscale-operator
    releaseName: tailscale-operator
    namespace: core-tailscale
    valuesFile: values.yaml
