apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: datamonster
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/datamonster-web
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: datamonster
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datamonster
  filterTags:
    pattern: '^(?P<ts>[0-9]+\.[0-9]+\.[0-9]+-[0-9]+)$'
    extract: '$ts'
  policy:
    alphabetical:
      order: desc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: datamonster-api
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/datamonster-api
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: datamonster-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datamonster-api
  filterTags:
    pattern: '^(?P<ts>[0-9]+\.[0-9]+\.[0-9]+-[0-9]+)$'
    extract: '$ts'
  policy:
    alphabetical:
      order: desc
