apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: datamonster
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/datamonster-web
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: datamonster
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datamonster
  filterTags:
    pattern: '^(?P<year>\d+)\.(?P<month>\d+)\.(?P<day>\d+)-(?P<build>\d+)$'
    extract: '$year$month$day$build'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: datamonster-api
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/datamonster-api
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: datamonster-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datamonster-api
  filterTags:
    pattern: '^(?P<year>\d+)\.(?P<month>\d+)\.(?P<day>\d+)-(?P<build>\d+)$'
    extract: '$year$month$day$build'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: glossary
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/glossary
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: glossary
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: glossary
  filterTags:
    pattern: '^v(?P<major>\d+)\.(?P<minor>\d+)$'
    extract: '$major.$minor'
  policy:
    semver:
      range: ">=0.0"
