apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: datamonster
  namespace: flux-system
spec:
  image: ghcr.io/failuretoload/datamonster-web
  interval: 5m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: datamonster
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datamonster
  policy:
    alphabetical:
      order: desc
