apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-longhorn
resources:
  - namespace.yaml
  - resources/ingress.yaml
helmGlobals:
  chartHome: charts/longhorn
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.10.1
    releaseName: longhorn
    namespace: core-longhorn
    valuesFile: resources/values.yaml
