apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      vaultUrl: "https://dm-homelab-vault.vault.azure.net"
      authType: ServicePrincipal
      tenantId: ""
      authSecretRef:
        clientId:
          name: azure-secret
          namespace: core-external-secrets
          key: client-id
        clientSecret:
          name: azure-secret
          namespace: core-external-secrets
          key: client-secret
        tenantId:
          name: azure-secret
          namespace: core-external-secrets
          key: tenant-id
