apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resources/ingress.yaml
  - resources/datamonster-updater.yaml
helmGlobals:
  chartHome: charts/argocd
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.4
    releaseName: argocd
    namespace: core-argocd
    valuesFile: resources/values.yaml
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 1.0.1
    releaseName: argocd-image-updater
    namespace: core-argocd
    valuesFile: resources/image-updater-values.yaml
