apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator-oauth.yaml
helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    releaseName: tailscale-operator
    namespace: core-tailscale
    version: 1.90.8
    valuesFile: values.yaml
