commonLabels:
  app.kubernetes.io/name: tailscale

oauth: {}

operatorConfig:
  hostname: homelab-k8s-operator
  defaultTags:
    - "tag:k8s-operator"
  
apiServerProxyConfig:
  mode: "false"

proxyConfig:
  defaultTags: "tag:k8s"

podAnnotations:
  io.cilium.no-track-port: "41641"
