apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - core-cilium.yaml
  - core-external-secrets.yaml
  - core-cert-manager.yaml
  - core-tailscale.yaml
  - core-argocd.yaml
  - core-metrics-server.yaml
