apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - core-cilium.yaml
  - core-external-secrets.yaml
  - core-cert-manager.yaml
  - core-traefik.yaml
  - core-cloudflared.yaml
  - core-tailscale.yaml
  - core-argocd.yaml
  - core-metrics-server.yaml
  - core-longhorn.yaml
  - core-postgres.yaml
  - core-grafana.yaml
  - core-loki.yaml
  - core-prometheus.yaml
  - core-alloy.yaml
  - core-image-updater.yaml
  - core-origin-ca-issuer-crds.yaml
  - core-origin-ca-issuer.yaml
  - core-valkey.yaml
  - datamonster.yaml
