apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lldap
  namespace: core-auth
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: lldap
      port:
        number: 17170
  tls:
    - hosts:
        - lldap
